[project]
name = "sqlds"
version = "0.0.2"
description = "use DS with SQL"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apyds>=0.0.7",
    "apyds-bnf>=0.0.7",
    "cloudpickle>=3.1.2",
    "egglog>=12.0.0",
    "loguru>=0.7.3",
    "sqlalchemy>=2.0.45",
]

[tool.ruff]
line-length = 120
