[project]
name = "sqlds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.0",
    "apyds>=0.0.7",
    "apyds-bnf>=0.0.7",
    "sqlalchemy>=2.0.45",
]

[tool.ruff]
line-length = 120
